import { Metadata } from 'next'
import './globals.css'
import Modal from '@/components/Modal'




export const metadata: Metadata = {
  title: 'Trello',
  description: 'Generated by Priyanshu',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-br from-blue-100 via-blue-300 to-blue-500 min-h-screen'>
        {children}
        <Modal/>
      </body>
    </html>
  )
}
